### ISSUE TITLE
float division by zero when k=1

### ISSUE THREAD

**Issue by w1ndy** [damjankuznar/pylof#7]
Hi,

When I'm trying to run example 2 on a different set of data, I got div-by-zero exceptions with some particular data. For example,

``` python
import lof
inst = [(1.,2.,3.),(2.,3.,4.),(1.,2.,4.),(1.,2.,1.)]
l = lof.outliers(1, inst)
```

produces

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lof.py", line 160, in outliers
    value = l.local_outlier_factor(k, instance)
  File "/lof.py", line 95, in local_outlier_factor
    return local_outlier_factor(min_pts, instance, self.instances, distance_function=self.distance_function)
  File "/lof.py", line 142, in local_outlier_factor
    instance_lrd = local_reachability_density(min_pts, instance, instances, **kwargs)
  File "/lof.py", line 134, in local_reachability_density
    return len(neighbours) / sum(reachability_distances_array)
ZeroDivisionError: float division by zero
```

I wonder if I'm doing anything wrong? Any help would be appreciated, thanks.

**Comment by damjankuznar** [comment]
I did some testing and it seems it is due to unfortunate choice of instances and parameters. The problem is that when instance `(2., 3., 4.)` is being tested if it is an outlier, the remaining instances (to which the chosen instance is being tested against) all have values 1. and 2. in the first two dimensions - e.g. `(1., 2., 3.)`. When this set of instances is then normalized (which is the default) those dimensions get squashed to 0. This effectively transforms the data into:
- instances `[(1.,2.,3.),(1.,2.,4.),(1.,2.,1.)]` into `[0.66666, 1., 0.]`
- tested instance `(2., 3., 4.)` into `(1.)`

Since the tested instance and the last instance in the set are the same, we get distance 0 which then causes the `ZeroDivisionError`.

To bypass this problem, you should either:
- use a different set of instances
- turn off normalization: `l = lof.outliers(1, inst, normalize=False)`
- increase the number of neighbors: : `l = lof.outliers(2, inst)`

I will try to add additional checks to the code and raise more meaningful errors / warnings.
